import { Account, AuditLog, CompanySettings, Permissions, User, Voucher } from '../types';
import { numberToWords } from './numberToWords';

export const ALL_PERMISSIONS: Permissions = {
  viewCreditVoucher: true,
  createCreditVoucher: true,
  editCreditVoucher: true,
  deleteCreditVoucher: true,

  viewDebitVoucher: true,
  createDebitVoucher: true,
  editDebitVoucher: true,
  deleteDebitVoucher: true,

  viewContraVoucher: true,
  createContraVoucher: true,
  editContraVoucher: true,
  deleteContraVoucher: true,

  viewJournalVoucher: true,
  createJournalVoucher: true,
  editJournalVoucher: true,
  deleteJournalVoucher: true,

  viewLedger: true,
  viewReports: true,

  viewAccounts: true,
  manageAccounts: true,

  manageUsers: true,
  manageSettings: true,
  viewAuditLogs: true,

  printVouchers: true,
  exportPdf: true,
};

export const DEFAULT_COMPANY_SETTINGS: CompanySettings = {
  companyName: 'Hertz Industrial & Power Solutions',
  tagline: 'Reliable Engineering, Power Generators & Commercial Supply',
  address: 'Plot 42-B, Industrial Area, Sector G-9, Commercial Avenue',
  phone: '+92 300 1234567 / +92 51 8899770',
  email: 'info@hertzpower.com',
  ntnOrTaxId: 'NTN: 4892011-8 | STRN: 19-00-4892-011',
  currencySymbol: 'Rs.',
  currencyName: 'Rupees',
  creditPrefix: 'CRV-2026-',
  debitPrefix: 'CPV-2026-',
  contraPrefix: 'CV-2026-',
  journalPrefix: 'JV-2026-',
  preparedByTitle: 'Accountant',
  checkedByTitle: 'Internal Auditor',
  approvedByTitle: 'Managing Director / Admin',
  receivedByTitle: 'Receiver / Payee',
  watermarkText: 'OFFICIAL VOUCHER',
  termsAndConditions: 'All transactions are strictly subject to terms of audited accounting standard. Computer generated voucher valid with authorized stamp.',
};

export const INITIAL_ACCOUNTS: Account[] = [
  // Assets - Cash & Bank
  {
    id: 'acc-101',
    code: '1001',
    name: 'Cash in Hand (Main Safe)',
    category: 'ASSET',
    type: 'CASH',
    openingBalance: 250000,
    currentBalance: 320000,
    description: 'Primary counter cash register & vault',
    isActive: true,
  },
  {
    id: 'acc-102',
    code: '1002',
    name: 'Cash in Hand (Petty Cash)',
    category: 'ASSET',
    type: 'CASH',
    openingBalance: 50000,
    currentBalance: 42500,
    description: 'Daily office petty expenses cash fund',
    isActive: true,
  },
  {
    id: 'acc-103',
    code: '1010',
    name: 'Meezan Bank (Islamic Corp A/C)',
    category: 'ASSET',
    type: 'BANK',
    openingBalance: 1200000,
    currentBalance: 1485000,
    bankAccountNumber: 'PK36MEZN00010203040506',
    bankName: 'Meezan Bank Ltd',
    description: 'Main operating current account',
    isActive: true,
  },
  {
    id: 'acc-104',
    code: '1011',
    name: 'Habib Bank Ltd (HBL Commercial)',
    category: 'ASSET',
    type: 'BANK',
    openingBalance: 850000,
    currentBalance: 720000,
    bankAccountNumber: 'PK12HABB00998877665544',
    bankName: 'Habib Bank Ltd',
    description: 'Secondary operational account for vendor transfers',
    isActive: true,
  },
  // Assets - Receivables / Customers
  {
    id: 'acc-201',
    code: '1050',
    name: 'Al-Farooq Mills & Engineering',
    category: 'ASSET',
    type: 'CUSTOMER',
    openingBalance: 420000,
    currentBalance: 285000,
    description: 'Corporate client - Industrial generators maintenance',
    isActive: true,
  },
  {
    id: 'acc-202',
    code: '1051',
    name: 'Royal Plaza Commercial Complex',
    category: 'ASSET',
    type: 'CUSTOMER',
    openingBalance: 180000,
    currentBalance: 0,
    description: 'Annual power backup contract client',
    isActive: true,
  },
  {
    id: 'acc-203',
    code: '1052',
    name: 'Metro City Hospitals Ltd',
    category: 'ASSET',
    type: 'CUSTOMER',
    openingBalance: 650000,
    currentBalance: 450000,
    description: 'Emergency generator overhaul services',
    isActive: true,
  },
  // Liabilities - Payables / Vendors
  {
    id: 'acc-301',
    code: '2001',
    name: 'Cummins & Perkins Spare Parts Co.',
    category: 'LIABILITY',
    type: 'VENDOR',
    openingBalance: 320000,
    currentBalance: 195000,
    description: 'Engine filter, valves, and spares supplier',
    isActive: true,
  },
  {
    id: 'acc-302',
    code: '2002',
    name: 'National Diesel & Lubricants Supplier',
    category: 'LIABILITY',
    type: 'VENDOR',
    openingBalance: 150000,
    currentBalance: 65000,
    description: 'Fuel and synthetic motor oils vendor',
    isActive: true,
  },
  // Income / Revenue
  {
    id: 'acc-401',
    code: '4001',
    name: 'Generator Sales Revenue',
    category: 'INCOME',
    type: 'INCOME',
    openingBalance: 0,
    currentBalance: 1850000,
    description: 'Revenue from 50kVA - 500kVA generator units',
    isActive: true,
  },
  {
    id: 'acc-402',
    code: '4002',
    name: 'Service & Maintenance Contracts',
    category: 'INCOME',
    type: 'INCOME',
    openingBalance: 0,
    currentBalance: 620000,
    description: 'Monthly service SLA income',
    isActive: true,
  },
  // Expenses
  {
    id: 'acc-501',
    code: '5001',
    name: 'Office & Workshop Rent',
    category: 'EXPENSE',
    type: 'EXPENSE',
    openingBalance: 0,
    currentBalance: 140000,
    description: 'Monthly premises rental',
    isActive: true,
  },
  {
    id: 'acc-502',
    code: '5002',
    name: 'Electricity & Utilities Bill',
    category: 'EXPENSE',
    type: 'EXPENSE',
    openingBalance: 0,
    currentBalance: 58000,
    description: 'Commercial power and water bills',
    isActive: true,
  },
  {
    id: 'acc-503',
    code: '5003',
    name: 'Staff Salaries & Overtime Expense',
    category: 'EXPENSE',
    type: 'EXPENSE',
    openingBalance: 0,
    currentBalance: 320000,
    description: 'Technician, sales, and office payroll',
    isActive: true,
  },
  {
    id: 'acc-504',
    code: '5004',
    name: 'Fuel & Logistics Expense',
    category: 'EXPENSE',
    type: 'EXPENSE',
    openingBalance: 0,
    currentBalance: 34500,
    description: 'Field engineer van fuel and transport',
    isActive: true,
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-admin',
    username: 'admin',
    name: 'Super Admin (Director)',
    email: 'admin@hertzpower.com',
    password: 'admin',
    role: 'ADMIN',
    isActive: true,
    permissions: ALL_PERMISSIONS,
    createdAt: '2026-01-01T08:00:00Z',
    lastLogin: '2026-08-22T09:45:00Z',
  },
  {
    id: 'user-accountant',
    username: 'accountant',
    name: 'Muhammad Tariq (Sr. Accountant)',
    email: 'tariq@hertzpower.com',
    password: 'password123',
    role: 'ACCOUNTANT',
    isActive: true,
    permissions: {
      ...ALL_PERMISSIONS,
      manageUsers: false,
      manageSettings: false,
      viewAuditLogs: false,
    },
    createdAt: '2026-02-10T10:00:00Z',
    lastLogin: '2026-08-21T16:30:00Z',
  },
  {
    id: 'user-cashier',
    username: 'cashier',
    name: 'Bilal Ahmed (Cashier / Counter)',
    email: 'bilal@hertzpower.com',
    password: 'password123',
    role: 'CASHIER',
    isActive: true,
    permissions: {
      ...ALL_PERMISSIONS,
      viewCreditVoucher: true,
      createCreditVoucher: true,
      editCreditVoucher: false,
      deleteCreditVoucher: false,
      viewDebitVoucher: true,
      createDebitVoucher: true,
      editDebitVoucher: false,
      deleteDebitVoucher: false,
      viewContraVoucher: false,
      createContraVoucher: false,
      editContraVoucher: false,
      deleteContraVoucher: false,
      viewJournalVoucher: false,
      createJournalVoucher: false,
      editJournalVoucher: false,
      deleteJournalVoucher: false,
      viewLedger: true,
      viewReports: false,
      viewAccounts: true,
      manageAccounts: false,
      manageUsers: false,
      manageSettings: false,
      viewAuditLogs: false,
      printVouchers: true,
      exportPdf: true,
    },
    createdAt: '2026-03-01T09:15:00Z',
    lastLogin: '2026-08-22T08:15:00Z',
  },
  {
    id: 'user-credit-only',
    username: 'receipt_agent',
    name: 'Usman Ali (Credit Receipt Desk Only)',
    email: 'usman@hertzpower.com',
    password: 'password123',
    role: 'CUSTOM',
    isActive: true,
    permissions: {
      viewCreditVoucher: true,
      createCreditVoucher: true,
      editCreditVoucher: true,
      deleteCreditVoucher: false,
      viewDebitVoucher: false,
      createDebitVoucher: false,
      editDebitVoucher: false,
      deleteDebitVoucher: false,
      viewContraVoucher: false,
      createContraVoucher: false,
      editContraVoucher: false,
      deleteContraVoucher: false,
      viewJournalVoucher: false,
      createJournalVoucher: false,
      editJournalVoucher: false,
      deleteJournalVoucher: false,
      viewLedger: false,
      viewReports: false,
      viewAccounts: true,
      manageAccounts: false,
      manageUsers: false,
      manageSettings: false,
      viewAuditLogs: false,
      printVouchers: true,
      exportPdf: true,
    },
    createdAt: '2026-04-15T11:00:00Z',
    lastLogin: '2026-08-20T14:20:00Z',
  },
  {
    id: 'user-auditor',
    username: 'auditor',
    name: 'Zahid Khan (External Auditor)',
    email: 'auditor@auditfirm.com',
    password: 'password123',
    role: 'AUDITOR',
    isActive: true,
    permissions: {
      viewCreditVoucher: true,
      createCreditVoucher: false,
      editCreditVoucher: false,
      deleteCreditVoucher: false,
      viewDebitVoucher: true,
      createDebitVoucher: false,
      editDebitVoucher: false,
      deleteDebitVoucher: false,
      viewContraVoucher: true,
      createContraVoucher: false,
      editContraVoucher: false,
      deleteContraVoucher: false,
      viewJournalVoucher: true,
      createJournalVoucher: false,
      editJournalVoucher: false,
      deleteJournalVoucher: false,
      viewLedger: true,
      viewReports: true,
      viewAccounts: true,
      manageAccounts: false,
      manageUsers: false,
      manageSettings: false,
      viewAuditLogs: true,
      printVouchers: true,
      exportPdf: true,
    },
    createdAt: '2026-05-01T12:00:00Z',
    lastLogin: '2026-08-18T17:00:00Z',
  },
];

export const INITIAL_VOUCHERS: Voucher[] = [
  // 1. Credit Voucher (Receipt)
  {
    id: 'vch-001',
    voucherNumber: 'CRV-2026-0001',
    type: 'CREDIT',
    date: '2026-08-15',
    paymentMethod: 'CHEQUE',
    referenceNumber: 'CHQ-8829104',
    chequeDate: '2026-08-15',
    bankName: 'Meezan Bank Ltd',
    paidToOrReceivedFrom: 'Al-Farooq Mills & Engineering',
    narration: 'Received partial payment against 250kVA Generator Maintenance SLA for July 2026',
    items: [
      {
        id: 'item-1',
        accountId: 'acc-103',
        accountName: 'Meezan Bank (Islamic Corp A/C)',
        accountCode: '1010',
        description: 'Cheque deposit from client clearing',
        debit: 135000,
        credit: 0,
      },
      {
        id: 'item-2',
        accountId: 'acc-201',
        accountName: 'Al-Farooq Mills & Engineering',
        accountCode: '1050',
        description: 'Clearance of Invoice # INV-892',
        debit: 0,
        credit: 135000,
      },
    ],
    totalAmount: 135000,
    amountInWords: numberToWords(135000, 'Rupees'),
    preparedBy: 'Muhammad Tariq',
    checkedBy: 'Zahid Khan',
    approvedBy: 'Super Admin',
    receivedBy: 'Al-Farooq Rep. Shahnawaz',
    status: 'POSTED',
    createdAt: '2026-08-15T10:30:00Z',
    updatedAt: '2026-08-15T10:30:00Z',
    createdByUserId: 'user-accountant',
    createdByName: 'Muhammad Tariq (Sr. Accountant)',
  },

  // 2. Credit Voucher (Cash Receipt)
  {
    id: 'vch-002',
    voucherNumber: 'CRV-2026-0002',
    type: 'CREDIT',
    date: '2026-08-18',
    paymentMethod: 'CASH',
    referenceNumber: 'CSH-REC-490',
    paidToOrReceivedFrom: 'Royal Plaza Commercial Complex',
    narration: 'Full & final cash payment for emergency circuit breaker & generator testing inspection',
    items: [
      {
        id: 'item-3',
        accountId: 'acc-101',
        accountName: 'Cash in Hand (Main Safe)',
        accountCode: '1001',
        description: 'Cash received on site counter',
        debit: 180000,
        credit: 0,
      },
      {
        id: 'item-4',
        accountId: 'acc-202',
        accountName: 'Royal Plaza Commercial Complex',
        accountCode: '1051',
        description: 'Account balance zeroed out',
        debit: 0,
        credit: 180000,
      },
    ],
    totalAmount: 180000,
    amountInWords: numberToWords(180000, 'Rupees'),
    preparedBy: 'Bilal Ahmed',
    checkedBy: 'Muhammad Tariq',
    approvedBy: 'Super Admin',
    receivedBy: 'Royal Plaza Admin',
    status: 'POSTED',
    createdAt: '2026-08-18T14:15:00Z',
    updatedAt: '2026-08-18T14:15:00Z',
    createdByUserId: 'user-cashier',
    createdByName: 'Bilal Ahmed (Cashier / Counter)',
  },

  // 3. Debit Voucher (Payment Voucher - Parts Purchase)
  {
    id: 'vch-003',
    voucherNumber: 'CPV-2026-0001',
    type: 'DEBIT',
    date: '2026-08-19',
    paymentMethod: 'BANK_TRANSFER',
    referenceNumber: 'FT-994821034',
    bankName: 'Habib Bank Ltd (HBL Commercial)',
    paidToOrReceivedFrom: 'Cummins & Perkins Spare Parts Co.',
    narration: 'Online IBFT payment against delivery of 6 sets of heavy-duty fuel filters and gasket kits',
    items: [
      {
        id: 'item-5',
        accountId: 'acc-301',
        accountName: 'Cummins & Perkins Spare Parts Co.',
        accountCode: '2001',
        description: 'Settlement of Bill # CPS-4402',
        debit: 125000,
        credit: 0,
      },
      {
        id: 'item-6',
        accountId: 'acc-104',
        accountName: 'Habib Bank Ltd (HBL Commercial)',
        accountCode: '1011',
        description: 'Online bank transfer deduction',
        debit: 0,
        credit: 125000,
      },
    ],
    totalAmount: 125000,
    amountInWords: numberToWords(125000, 'Rupees'),
    preparedBy: 'Muhammad Tariq',
    checkedBy: 'Muhammad Tariq',
    approvedBy: 'Super Admin',
    receivedBy: 'Cummins Accounts Dept',
    status: 'POSTED',
    createdAt: '2026-08-19T11:45:00Z',
    updatedAt: '2026-08-19T11:45:00Z',
    createdByUserId: 'user-accountant',
    createdByName: 'Muhammad Tariq (Sr. Accountant)',
  },

  // 4. Debit Voucher (Cash Expense Payment)
  {
    id: 'vch-004',
    voucherNumber: 'CPV-2026-0002',
    type: 'DEBIT',
    date: '2026-08-20',
    paymentMethod: 'CASH',
    referenceNumber: 'VOUCH-EXP-088',
    paidToOrReceivedFrom: 'Property Landlord - Haji Abdul Ghani',
    narration: 'Office and main workshop rent for the month of August 2026',
    items: [
      {
        id: 'item-7',
        accountId: 'acc-501',
        accountName: 'Office & Workshop Rent',
        accountCode: '5001',
        description: 'Premises rent voucher',
        debit: 140000,
        credit: 0,
      },
      {
        id: 'item-8',
        accountId: 'acc-101',
        accountName: 'Cash in Hand (Main Safe)',
        accountCode: '1001',
        description: 'Cash payment from safe',
        debit: 0,
        credit: 140000,
      },
    ],
    totalAmount: 140000,
    amountInWords: numberToWords(140000, 'Rupees'),
    preparedBy: 'Bilal Ahmed',
    checkedBy: 'Muhammad Tariq',
    approvedBy: 'Super Admin',
    receivedBy: 'Haji Abdul Ghani',
    status: 'POSTED',
    createdAt: '2026-08-20T09:20:00Z',
    updatedAt: '2026-08-20T09:20:00Z',
    createdByUserId: 'user-cashier',
    createdByName: 'Bilal Ahmed (Cashier / Counter)',
  },

  // 5. Contra Voucher (Cash Deposit: Cash -> Bank)
  {
    id: 'vch-005',
    voucherNumber: 'CV-2026-0001',
    type: 'CONTRA',
    date: '2026-08-21',
    paymentMethod: 'CASH',
    referenceNumber: 'DEP-SLIP-773291',
    bankName: 'Meezan Bank Ltd',
    paidToOrReceivedFrom: 'Meezan Bank Account Deposit',
    narration: 'Deposited excess counter cash from Main Safe into Meezan Islamic Current Account',
    items: [
      {
        id: 'item-9',
        accountId: 'acc-103',
        accountName: 'Meezan Bank (Islamic Corp A/C)',
        accountCode: '1010',
        description: 'Cash deposit via branch slip',
        debit: 150000,
        credit: 0,
      },
      {
        id: 'item-10',
        accountId: 'acc-101',
        accountName: 'Cash in Hand (Main Safe)',
        accountCode: '1001',
        description: 'Cash transferred out of safe to bank',
        debit: 0,
        credit: 150000,
      },
    ],
    totalAmount: 150000,
    amountInWords: numberToWords(150000, 'Rupees'),
    preparedBy: 'Muhammad Tariq',
    checkedBy: 'Muhammad Tariq',
    approvedBy: 'Super Admin',
    receivedBy: 'Meezan Bank Cashier',
    status: 'POSTED',
    createdAt: '2026-08-21T15:00:00Z',
    updatedAt: '2026-08-21T15:00:00Z',
    createdByUserId: 'user-accountant',
    createdByName: 'Muhammad Tariq (Sr. Accountant)',
  },

  // 6. Contra Voucher (Cash Withdrawal for Petty Fund: Bank -> Petty Cash)
  {
    id: 'vch-006',
    voucherNumber: 'CV-2026-0002',
    type: 'CONTRA',
    date: '2026-08-21',
    paymentMethod: 'CHEQUE',
    referenceNumber: 'CHQ-SELF-10992',
    chequeDate: '2026-08-21',
    bankName: 'Habib Bank Ltd',
    paidToOrReceivedFrom: 'Self Petty Cash Replenishment',
    narration: 'Withdrew cash via self cheque from HBL to replenish petty cash expenses drawer',
    items: [
      {
        id: 'item-11',
        accountId: 'acc-102',
        accountName: 'Cash in Hand (Petty Cash)',
        accountCode: '1002',
        description: 'Petty cash refill',
        debit: 25000,
        credit: 0,
      },
      {
        id: 'item-12',
        accountId: 'acc-104',
        accountName: 'Habib Bank Ltd (HBL Commercial)',
        accountCode: '1011',
        description: 'Cheque self withdrawal',
        debit: 0,
        credit: 25000,
      },
    ],
    totalAmount: 25000,
    amountInWords: numberToWords(25000, 'Rupees'),
    preparedBy: 'Muhammad Tariq',
    checkedBy: 'Muhammad Tariq',
    approvedBy: 'Super Admin',
    receivedBy: 'Bilal Ahmed (Petty Cashier)',
    status: 'POSTED',
    createdAt: '2026-08-21T16:10:00Z',
    updatedAt: '2026-08-21T16:10:00Z',
    createdByUserId: 'user-accountant',
    createdByName: 'Muhammad Tariq (Sr. Accountant)',
  },

  // 7. Journal Voucher (Adjustment / Multi-entry / Non-Cash)
  {
    id: 'vch-007',
    voucherNumber: 'JV-2026-0001',
    type: 'JOURNAL',
    date: '2026-08-22',
    referenceNumber: 'ADJ-SAL-08-26',
    paidToOrReceivedFrom: 'Monthly Staff Payroll Adjustment',
    narration: 'Booking accrued technician and sales team salaries for the active payroll cycle',
    items: [
      {
        id: 'item-13',
        accountId: 'acc-503',
        accountName: 'Staff Salaries & Overtime Expense',
        accountCode: '5003',
        description: 'Salary expense booking for August',
        debit: 320000,
        credit: 0,
      },
      {
        id: 'item-14',
        accountId: 'acc-103',
        accountName: 'Meezan Bank (Islamic Corp A/C)',
        accountCode: '1010',
        description: 'Direct payroll direct deposit disbursement',
        debit: 0,
        credit: 320000,
      },
    ],
    totalAmount: 320000,
    amountInWords: numberToWords(320000, 'Rupees'),
    preparedBy: 'Muhammad Tariq',
    checkedBy: 'Zahid Khan',
    approvedBy: 'Super Admin',
    receivedBy: 'Payroll Register',
    status: 'POSTED',
    createdAt: '2026-08-22T08:30:00Z',
    updatedAt: '2026-08-22T08:30:00Z',
    createdByUserId: 'user-accountant',
    createdByName: 'Muhammad Tariq (Sr. Accountant)',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    timestamp: '2026-08-22T09:45:00Z',
    userId: 'user-admin',
    userName: 'Super Admin (Director)',
    action: 'LOGIN',
    details: 'Logged into system with full administrative privileges',
  },
  {
    id: 'log-2',
    timestamp: '2026-08-22T08:30:00Z',
    userId: 'user-accountant',
    userName: 'Muhammad Tariq (Sr. Accountant)',
    action: 'CREATE_VOUCHER',
    voucherNumber: 'JV-2026-0001',
    details: 'Created Journal Voucher for Staff Payroll Booking (Rs. 320,000)',
  },
  {
    id: 'log-3',
    timestamp: '2026-08-21T16:10:00Z',
    userId: 'user-accountant',
    userName: 'Muhammad Tariq (Sr. Accountant)',
    action: 'CREATE_VOUCHER',
    voucherNumber: 'CV-2026-0002',
    details: 'Created Contra Voucher for Bank Cheque Self Cash Withdrawal (Rs. 25,000)',
  },
  {
    id: 'log-4',
    timestamp: '2026-08-21T15:00:00Z',
    userId: 'user-accountant',
    userName: 'Muhammad Tariq (Sr. Accountant)',
    action: 'CREATE_VOUCHER',
    voucherNumber: 'CV-2026-0001',
    details: 'Created Contra Voucher for Cash Safe deposit to Meezan Bank (Rs. 150,000)',
  },
  {
    id: 'log-5',
    timestamp: '2026-08-20T09:20:00Z',
    userId: 'user-cashier',
    userName: 'Bilal Ahmed (Cashier / Counter)',
    action: 'CREATE_VOUCHER',
    voucherNumber: 'CPV-2026-0002',
    details: 'Created Debit Payment Voucher for Workshop Rent (Rs. 140,000)',
  },
];
